# Configurations
title:            雪宝的博客
longtitle:        柠檬雪宝的博客，或许不只是博客
author:           柠檬雪宝（Sherbet Lemon）
description: >
  In solitude, where we are least alone.

version:          1.0
gitbook_version:  3.2.3

url:              'https://diary.sherbetlemon.org'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
# favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:title

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  posts:
    output: true
    permalink: /:title
  pages:
    output: true
    permalink: /:title
  others:
    output: true
    permalink: /:title

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  
extra_footer_js:
  - https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js
  - assets/gitbook/minipen.js
